service: api
frameworkVersion: '>=1.1.0'
plugins:
  - serverless-offline
package:
  individually: true
  excludeDevDependencies: false
provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
functions:
  hello-world:
    handler: src/handler.helloWorld
    events:
      - http:
          method: get
          path: hello-world
  nestjs:
    handler: src/handler.handler
    events:
      - http:
          method: get
          path: nestjs
