service: api
frameworkVersion: '>=1.1.0'
plugins:
  - serverless-offline
# Uncomment this to avoid cold start on serverless-offline
custom:
  serverless-offline:
    allowCache: true
package:
  individually: true
  excludeDevDependencies: false
provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
functions:
  express:
    handler: src/handler.express
    events:
      - http:
          method: get
          path: express
  fastify:
    handler: src/handler.fastify
    events:
      - http:
          method: get
          path: fastify
